version: '3.8'

services:
  postgres:
    image: postgres:14.18
    user: "${USER_UID}:${USER_GID}"
    environment:
      POSTGRES_USER: app
      POSTGRES_DB: appdb
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    volumes:
      #- /srv/data/postgres:/var/lib/postgresql/data/pgdata
      - "${WORKING_DIR}/data/postgres/appdb.sql:/docker-entrypoint-initdb.d/appdb.sql"
      #- "${WORKING_DIR}/config/postgres/restore.sh:/docker-entrypoint-initdb.d/restore.sh"
      #- "${WORKING_DIR}/data/postgres/appdb.dump:/docker-entrypoint-initdb.d/appdb.dump"
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  adminer:
    image: adminer:5.3.0
    user: "${USER_UID}:${USER_GID}"
    restart: always
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8080 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana:12.1.0-ubuntu
    user: "${USER_UID}:${USER_GID}"
    secrets:
      - grafana_admin_password
      - postgres_password
    environment:
      - GF_LOG_FILTERS=provisioning.dashboard:debug
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_admin_password
      #- GF_SECURITY_ADMIN_API_KEY=bootstrap-admin-key
    ports:
      - 8081:3000
    volumes:
        - "${WORKING_DIR}/config/grafana/provisioning:/etc/grafana/provisioning"
    healthcheck:
      test: ["CMD", "bash", "-c", "curl -sf http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  postgres_password:
    external: true
  grafana_admin_password:
    external: true
